
language: python
deploy:
  provider: heroku
  buildpack: python
  api_key:
    secure: 9d74c83b-d494-468c-b5a7-bcff322c504f
  strategy: git
  app: vgam
  on:
    repo: 3kybika/VGAM-project

sudo: required

services:
  - docker

install: true

script:
  - docker images --all
  - docker build -t registry.heroku.com/vgam/web .
  - docker push registry.heroku.com/vgam/web
