language: python 

    python: 

      - "2.7"

    services: 

      - mysql
      - nginx

    env: 

      -DJANGO=1.8 DB=mysql
    install: 

    install:
  - pip install gunicorn


    before_script: 

      - mysql -e 'create database VGAM_db;' -u root
    script: 

      - gunicorn vgam.wsgi
