sudo: required 
dist: trusty 
language: python
- "2.7"

branches: 
only: 
- master 

#----------------------------------------------— 
before_install:
-sudo apt-get update
#----DB configuration?-------------------------

instal: true 
- pip install .
- pip install gunicorn
- pip install -e django

before_script:
  - sudo apt-get install nginx 
  - sudo rm /etc/nginx/sites-enabled/*
  - sudo cp vgam.conf /etc/nginx/sites-enabled/vgam.conf
 # - sudo /etc/init.d/nginx restart
  - sudo nginx service restart
  - mkdir /vgam
  - sudo cp vgam/ /vgam
  
script: 
- gunicorn /vgam/vgam.wsgi

deploy:
 provider: heroku

 
