# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 15:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.TextField(max_length=100)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('NumOfLikes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Avatar', models.ImageField(default='default.jpg', upload_to='avatars/%Y/%m/%d/%H/')),
                ('AboutMe', models.TextField(max_length=100, null=True)),
                ('organisation', models.TextField(max_length=100, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='rating.Profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentToExpert', to='rating.Profile'),
        ),
    ]
