# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20171106_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('patronymic', models.CharField(max_length=20)),
                ('custom_text', models.CharField(default='', max_length=200)),
                ('points', models.IntegerField(default=0)),
                ('average_case_size', models.IntegerField(default=0)),
                ('average_reward', models.IntegerField(default=0)),
                ('average_return_level', models.IntegerField(default=0)),
                ('has_complaint', models.BooleanField(default=False)),
                ('has_disqualification', models.BooleanField(default=False)),
                ('has_disciplinary_action', models.BooleanField(default=False)),
                ('SRO', models.CharField(max_length=20)),
                ('regions', models.CharField(max_length=300)),
                ('industries', models.CharField(max_length=300)),
            ],
        ),
    ]
