# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
